// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6vlZNp20zir0E4aIiUpVM6dSQqjecvig',
    appId: '1:792316857839:android:84edf2d6172bffc4',
    messagingSenderId: '792316857839',
    projectId: 'dubstepfm-25bd3',
    databaseURL: 'https://dubstepfm-25bd3.firebaseio.com',
    storageBucket: 'dubstepfm-25bd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP6z_W52ZHLZodBQlyMEqLEMqe0GenpX0',
    appId: '1:792316857839:ios:86a9ba1b9605220c04fa1a',
    messagingSenderId: '792316857839',
    projectId: 'dubstepfm-25bd3',
    databaseURL: 'https://dubstepfm-25bd3.firebaseio.com',
    storageBucket: 'dubstepfm-25bd3.firebasestorage.app',
    iosBundleId: 'com.wishnewjam.dubstepfm',
  );
}
